[project]
name = "jackofalltrades"
version = "0.0.3"
readme = "README.md"
requires-python = ">=3.10"
description = "A simple, JAX-accelerated machine learning toolkit with GPU support and vectorized operations"
authors = [{ name = "Ojas Patil", email = "patil.ojas.250202@gmail.com" }]
license = "MIT"
dependencies = ["pandas>=2.2.2", "numpy>=1.26.4", "scikit-learn>=1.5.0", "matplotlib>=3.9.0", "jax>=0.4.28", "jaxlib>=0.4.28", "tqdm>=4.66.0", "tensorflow>=2.14.1", "optax>=0.2.2", "flax>=0.8.1", "torch>=1.10.0"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["jackofalltrades.test", "jackofalltrades.test.*"]

[tool.setuptools.package-data]
jackofalltrades = ["datasets/*.csv", "*.txt"]

[tool.setuptools]
include-package-data = true

[project.urls]
Homepage = "https://jackofalltrades-py.netlify.app/"
Documentation = "https://jackofalltrades-py.netlify.app/"